#!/bin/bash

BASE_URL="seedbox_url"

urldecode() {
    printf '%b' "${1//%/\\x}"
}

play_directory() {
    local dir_url="$1"
    local selected_file="$2"
    
    local playlist=$(curl -s "$dir_url/" | 
        grep -oP '(?<=href=")[^"]+' | 
        grep -E '\.(mp4|mkv|avi|webm)$')
    
    local start_index=$(($(echo "$playlist" | grep -n "$selected_file" | cut -d: -f1) - 1))
    
    echo "$playlist" | 
        sed "s|^|$dir_url/|" |
        mpv --playlist=- --playlist-start="$start_index"
}

navigate_and_play() {
    local current_url="$1"
    
    while true; do
        SELECTION=$(curl -s "$current_url/" | 
            grep -oP '(?<=href=")[^"]+' | 
            while read -r line; do
                echo -e "$(urldecode "$line")\t$line"
            done |
            fzf --with-nth=1 --delimiter='\t' --preview 'echo {1}' |
            cut -f2)
        
        [[ -z "$SELECTION" ]] && exit
        
        if [[ "$SELECTION" == */ ]]; then
            current_url="${current_url}/${SELECTION%/}"
        else
            play_directory "$current_url" "$SELECTION"
            break
        fi
    done
}

navigate_and_play "$BASE_URL"